### ISSUE TITLE
"stale while revalidate" claim is misleading, should be "stale-if-error"

### ISSUE THREAD

**Issue by RichardBradley** [bbc/ipr-php-cache#3]
I was excited to see that the library claims to offer "stale-while-revalidate" caching, as that's really hard to implement in PHP. Unfortunately, after reading more, I was disappointed (but not surprised; this is a common misunderstanding AFAICT) :-(

So far as I can tell, this library doesn't give "stale-while-revalidate" caching in the commonly understood sense of the term as used in HTTP, see e.g. [RFC-5861](https://tools.ietf.org/html/rfc5861#section-3) (emphasis added):

> If a cached response is served stale due to the presence of this
   extension, the cache SHOULD attempt to revalidate it **while still
   serving stale responses** (i.e., without blocking).
> ...
> [the stale-while-revalidate settings] determine how likely it is that all requests
   will be served **without delay**

The HTTP "stale-while-revalidate" feature is *asynchronous* and a stale-while-revalidate cache will refetch the resource in the background while serving the stale content to clients without delay.

That is very hard (or impossible?) to achieve in PHP, as it is a single-threaded language :-(

This feature should be described as falling back to stale content if the re-fetch fails, i.e. HTTP "stale-if-error" (see same RFC). If a cache item is stale, the re-fetch will happen synchronously in this library, blocking the request.

In a correctly configured "stale-while-revalidate" cache (with sufficient traffic load), no client will ever see a delay due to fetching. In this cache, there will always be some proportion of clients who will see a delay due to the underlying fetch.

**Comment by alexgisby** [comment]
Hi Richard, apologies for the slow reply.

I'm not sure that I agree with you. The actual revalidation of the objects in cache is something that is extremely user-land and not something that this library can or should handle. As you point out, PHP itself is single threaded, but there are several options for performing the revalidation asynchronously (messages on SQS queues, crons etc), but all of that is highly tied to the design and architecture of your application, and not something that this lib could have any hope to support.

This lib merely includes the idea of "staleness" within cache objects, allowing applications to make intelligent decisions based on that, of which, an async refresh is one option, or stale-while-error another.

This is a criticism that could be levelled against the [webservicekit](http://github.com/bbc/ipr-php-webservicekit) library that does perform something closer to stale-on-error than an async stale-while-revalidate, but it feels decidedly out of scope for this lib to be responsible for refresh policies.

Hope that clears up the confusion!

**Comment by RichardBradley** [comment]
I don't agree at all.

If you have a look at the example code [provided in the README docs](https://github.com/bbc/ipr-php-cache#stale-while-revalidate-caching) for the stale-while-revalidate feature in `ipr-php-cache`, the data fetch looks like:

```
$item = $cache->get('hello_world');
if ($item->isStale() || $item->isExpired()) {
    $data = someExpensiveOperation();

    if ($data) {
        // We got a good response, let's cache that:
        $item->setData($data);
        $item->setBestBefore(60); // start re-fetching after 1 minute
        $item->setLifetime(300); // flush from cache at 5 minutes

        $cache->save($item);
    }
}
```

I think this is quite clearly `stale-if-error` behaviour, since the "someExpensiveOperation" call is blocking in PHP. For the lib to provide `stale-while-revalidate` behaviour, you would need to return the stale value after the "if ($item->isStale())" call and proceed with a cache update **on a background thread**.

Is your argument is that, because there could be stale-while-revalidate behaviour implemented in an external system to a PHP app during the "someExpensiveOperation" call, then this **could** in fact be "stale-while-revalidate", according to "user-land" details which are out of scope here? That doesn't seem very likely. Even your example code has named the refresh op "someExpensiveOperation()" and not e.g. "kickOffBackgroundRefresh()". What does the "$data" value returned by "someExpensiveOperation" mean in that scenario? Anyway, in that case it would not be the `ipr-php-cache` which is providing S-W-R, but some mysterious external system.

It's up to you what you write here, of course. I just think it's going to lead to confusion if you use a term with a very specific technical meaning but you're not actually following the spec, [RFC-5861](https://tools.ietf.org/html/rfc5861)

**Comment by alexgisby** [comment]
The example given in the readme is an almost pseudo-code example of how to implement, assuming that library users would see the themes contained within and implement how they wish. A more complete example would be:

```php
$item = $cache->get('hello_world');
if ($item->isStale() && !$item->isExpired()) {
    // Async refresh
    putOnRevalidateQueue('hello_world');
} elseif ($item->isExpired()) {
    // Force a reload now
    $data = someExpensiveOperation();

    if ($data) {
        // We got a good response, let's cache that:
        $item->setData($data);
        $item->setBestBefore(60); // start re-fetching after 1 minute
        $item->setLifetime(300); // flush from cache at 5 minutes

        $cache->save($item);
    }
}

echo $item->getData();
```

However we would assume that the API given and an understanding of the concepts involved would lead people to this form of solution.

I'm sorry for your disappointment that this library doesn't do what you wish, and would advise that if you want a cache lib that handles async-refresh for you, you need to look elsewhere or write one of your own, since this lib can't include such functionality.
